name = "BasicBlackHoleSim"
uuid = "85eb58d7-e894-4321-a0d0-3cd5d3813362"
version = "0.1.0"
authors = ["jonesdwill <jonesdwill@outlook.com>"]

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Colors = "0.13.1"
DataFrames = "1.8.1"
DifferentialEquations = "7.17.0"
FileIO = "1.17.1"
ForwardDiff = "1.3.0"
Images = "0.26.2"
LinearAlgebra = "1.12.0"
PlotlyJS = "0.18.17"
Plots = "1.41.2"
Printf = "1.11.0"
RecursiveArrayTools = "3.39.0"
Revise = "3.12.3"
Test = "1.11.0"
